FROM php:fpm-alpine

# Extract the source code so we can build against it.
RUN apk --no-cache add git openssh vim 
RUN docker-php-source extract
RUN git clone https://github.com/JustinLawrenceMS/truthy.git
